# Contrastive and Triplet loss in one program.
IN ORDER OF NEED:
+ We can choose which variant we want - Contrastive or Triplet. 
+ We want also, to compare performance of this two variants  (for now, based on the old metrics (the result will be inaccurate)
+ New special constructed metrics that is useful in our case
+ Module helping in creating models. The unchanging part and the variable part
+ Function that checking and printing wrong predictions of the model
+ TODO comments
+ Zaimplementowanie sposobu do wyświetlania podsumowania budowy modelu triplet loss
+ Poszukanie innych zbiorów danych
+ Dowiedzieć się jak zapisywać modele do pliku
+ <> IF something important put here </>

In [13]:
import tensorflow as tf
import keras
import numpy as np
import keras.backend as K
x = [23.3, -45.2, 2.10, -0.01, 5.50]
# y = [-10.2, 23.3, 0.01, -20.2, 1.23]
y = [23.3, -45.2, 2.19, -0.11, 5.50]
x1 = np.array([23.3, -45.2, 2.10, -0.01, 5.50])
# y1 = np.array([-10.2, 23.3, 0.01, -20.2, 1.23])
y1 = np.array([23.3, -45.2, 2.19, -0.11, 5.50])
roznica = x1 - y1
print(roznica)
x_norm = K.l2_normalize(x)
y_norm = K.l2_normalize(y)
y_norm_roznica = K.l2_normalize(roznica)
print(x_norm)
print(y_norm)
print(x_norm - y_norm)
print(y_norm_roznica)


# vector_norm =  keras.layers.Lambda(lambda x: tf.math.l2_normalalize(x, axis=1))(x)
# print(vector_norm)

[ 0.    0.   -0.09  0.1   0.  ]
tf.Tensor(
[ 4.55151886e-01 -8.82955670e-01  4.10222709e-02 -1.95344153e-04
  1.07439294e-01], shape=(5,), dtype=float32)
tf.Tensor([ 0.45511734 -0.8828886   0.04277712 -0.00214862  0.10743114], shape=(5,), dtype=float32)
tf.Tensor(
[ 3.4540892e-05 -6.7055225e-05 -1.7548539e-03  1.9532784e-03
  8.1583858e-06], shape=(5,), dtype=float32)
tf.Tensor([ 0.          0.         -0.66896473  0.74329415  0.        ], shape=(5,), dtype=float64)


In [14]:
suma_1= np.sum((x_norm-y_norm)**2)
suma_2 = np.sum(y_norm_roznica**2)
print("Suma1:", suma_1)
print("Suma2:", suma_2)

Suma1: 6.9005646e-06
Suma2: 1.0
